[package]
name = "solution"
version = "0.1.0"
authors = ["Dan Enman <enmand@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent = { path = "../advent" }

[[bin]]
name = "solution"
path = "main.rs"
